<a href="https://colab.research.google.com/github/aquibaijaz11/finaldraft/blob/master/Salaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the libraries

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Importing the dataset

In [21]:
dataset = pd.read_csv('Book4.csv')

In [22]:
dataset.head()

Types of Products  ...  Perchase amount ($)
0                  2  ...                  837
1                  2  ...                 1533
2                  3  ...                 1577
3                  4  ...                 1055
4                  5  ...                 1279

[5 rows x 7 columns]

In [23]:
dataset.describe()

Types of Products  ...  Perchase amount ($)
count             500.00  ...               500.00
mean                3.23  ...              1178.55
std                 1.29  ...               295.18
min                 1.00  ...               672.00
25%                 2.00  ...               919.75
50%                 3.00  ...              1202.50
75%                 4.00  ...              1430.25
max                 5.00  ...              1669.00

[8 rows x 7 columns]

In [24]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [25]:
print(X)

[[ 2. 30.  0.  3.  0.  2.]
 [ 2. 37.  1.  6.  1.  2.]
 [ 3. 37.  0.  6.  1.  1.]
 ...
 [ 2. 38.  0.  5.  0.  0.]
 [ 4. 36.  1.  2.  0.  2.]
 [ 2. 58.  0.  6.  0.  0.]]


In [26]:
print(y)

[ 837 1533 1577 1055 1279 1662  758 1015 1277  885  901  757  703 1150
  971 1472 1235 1183 1008  880  683 1137 1309 1313  877 1547  694 1551
 1279 1121 1248 1200  972 1403 1467  895 1181  833 1198 1105  980 1238
 1280  822 1356 1295 1308  913 1257  974 1398 1431  817 1519 1393 1638
 1383  978 1384 1052 1518  821  981 1275 1627  684 1214  902 1373  758
 1492 1274 1523  856 1513 1373 1400  703 1537 1632 1579 1458  923  939
  992 1027 1345 1622 1107 1163 1585  694 1311  923 1312 1137 1185 1480
  756 1510  804  843  678 1661  733 1508 1547  822  856 1567 1328  872
  724 1317  787 1043 1550  892  719  861 1517  949 1008 1592 1567  949
  925  979 1307 1049 1563 1558 1205 1148  822 1313  717 1117  859  986
 1522  738 1381  781 1498 1389  725  785 1608 1003 1097  854 1361 1339
  898 1264  977 1079 1538  905  940  809 1636 1293 1085 1390 1025 1185
  867  764 1458 1086  981  722 1428 1414  984 1668 1005 1614 1071  907
 1094 1007  672 1489 1029 1637 1013 1145  897  923 1309 1332 1509 1368
  738 

Filling the missing values

In [27]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:2])
X[:, 1:2] = imputer.transform(X[:, 1:2])

In [28]:
print(X)

[[ 2. 30.  0.  3.  0.  2.]
 [ 2. 37.  1.  6.  1.  2.]
 [ 3. 37.  0.  6.  1.  1.]
 ...
 [ 2. 38.  0.  5.  0.  0.]
 [ 4. 36.  1.  2.  0.  2.]
 [ 2. 58.  0.  6.  0.  0.]]


Splitiing the dataset into training set and test set

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

Creating a multiple linear regressor model

In [30]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

Predicting the results

In [31]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1245.24 1585.  ]
 [1180.19  999.  ]
 [1198.75 1316.  ]
 [1179.87 1068.  ]
 [1245.   1494.  ]
 [1244.57 1472.  ]
 [1203.34 1197.  ]
 [1310.54  695.  ]
 [1144.11  905.  ]
 [1302.6  1339.  ]
 [1164.86 1606.  ]
 [1081.26  768.  ]
 [1218.78  931.  ]
 [1213.65 1547.  ]
 [1094.01 1086.  ]
 [1243.3  1312.  ]
 [1210.53  870.  ]
 [1183.39 1114.  ]
 [1147.87  898.  ]
 [1203.    833.  ]
 [1177.57  680.  ]
 [1202.58 1488.  ]
 [1159.44  842.  ]
 [1208.35  856.  ]
 [1202.46 1295.  ]
 [1218.37 1408.  ]
 [1240.95 1137.  ]
 [1196.1   677.  ]
 [1286.51 1185.  ]
 [1092.29 1273.  ]
 [1273.89  742.  ]
 [1181.71  719.  ]
 [1268.84 1567.  ]
 [1065.68  923.  ]
 [1060.3  1425.  ]
 [1193.78 1624.  ]
 [1208.34 1073.  ]
 [1170.41 1565.  ]
 [1166.53 1367.  ]
 [1208.95 1586.  ]
 [1266.66 1231.  ]
 [1191.77 1308.  ]
 [1104.    937.  ]
 [1192.63 1638.  ]
 [1138.53 1400.  ]
 [1129.   1533.  ]
 [1156.49  803.  ]
 [1223.91  691.  ]
 [1251.54 1275.  ]
 [1164.86  678.  ]
 [1162.27 1037.  ]
 [1200.51 1458.  ]
 [1090.5   8

Comparing the actual and predcited results

In [32]:
dataframe = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})  
dataframe

Actual  Predicted
0      1585    1245.24
1       999    1180.19
2      1316    1198.75
3      1068    1179.87
4      1494    1245.00
..      ...        ...
145    1279    1157.94
146     836    1136.54
147     884    1100.96
148    1550    1231.25
149    1662    1216.50

[150 rows x 2 columns]

Checking the accuracy of the model

In [33]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = regressor, X = X_train, y = y_train, cv = 3)
print("Accuracy: {} %".format(accuracies.mean()*100))
print("Standard Deviation: {} %".format(accuracies.std()*100))

Accuracy: -1.1396389568608702 %
Standard Deviation: 4.510521478529371 %


Installing Lazy Regressor

In [34]:
!pip install lazypredict

Importing the lazy regressor

In [35]:
from lazypredict.Supervised import LazyRegressor as LR
lazy_pred = LR()
regressor, predictions = lazy_pred.fit(X_train, X_test, y_train, y_test)

100%|██████████| 42/42 [00:02<00:00, 16.88it/s]


Displaying the results of the lazy regressor model

In [36]:
regressor

Adjusted R-Squared  ...  Time Taken
Model                                              ...            
OrthogonalMatchingPursuit                   -0.03  ...        0.01
LassoLars                                   -0.04  ...        0.02
DummyRegressor                              -0.05  ...        0.01
NuSVR                                       -0.05  ...        0.03
ElasticNetCV                                -0.05  ...        0.06
GeneralizedLinearRegressor                  -0.05  ...        0.03
TweedieRegressor                            -0.05  ...        0.01
LarsCV                                      -0.05  ...        0.06
LassoLarsCV                                 -0.05  ...        0.03
GammaRegressor                              -0.05  ...        0.02
BayesianRidge                               -0.05  ...        0.01
LassoCV                                     -0.05  ...        0.09
ElasticNet                                  -0.05  ...        0.01
LassoLarsIC                                 -0.06  ...        0.01
SVR                                         -0.06  ...        0.02
OrthogonalMatchingPursuitCV                 -0.07  ...        0.02
Lasso                                       -0.07  ...        0.03
RidgeCV                                     -0.07  ...        0.01
Ridge                                       -0.07  ...        0.01
SGDRegressor                                -0.07  ...        0.01
TransformedTargetRegressor                  -0.07  ...        0.01
LinearRegression                            -0.07  ...        0.02
Lars                                        -0.07  ...        0.03
PoissonRegressor                            -0.07  ...        0.02
HuberRegressor                              -0.09  ...        0.02
PassiveAggressiveRegressor                  -0.10  ...        0.04
AdaBoostRegressor                           -0.13  ...        0.03
RandomForestRegressor                       -0.20  ...        0.22
GradientBoostingRegressor                   -0.23  ...        0.11
KNeighborsRegressor                         -0.25  ...        0.01
HistGradientBoostingRegressor               -0.28  ...        0.17
LGBMRegressor                               -0.29  ...        0.04
BaggingRegressor                            -0.29  ...        0.03
RANSACRegressor                             -0.38  ...        0.07
ExtraTreesRegressor                         -0.39  ...        0.15
XGBRegressor                                -0.48  ...        0.05
ExtraTreeRegressor                          -1.21  ...        0.01
DecisionTreeRegressor                       -1.23  ...        0.01
LinearSVR                                   -6.97  ...        0.01
MLPRegressor                               -13.11  ...        0.81
KernelRidge                                -14.11  ...        0.04
GaussianProcessRegressor                   -19.24  ...        0.04

[42 rows x 4 columns]